# Introduction to Python3: Numpy

## El paquete NumPy

Python está organizado en módulos que son archivos con extensión .py que contienen funciones, variables y otros objetos; los paquetes son conjuntos de módulos. Cuando se quiere utilizar objetos que están definidos en un módulo se tiene que _importarlo_ y una vez hecho esto utilizar el operado . para descender en la jerarquía de paquetes y acceder al objeto necesitado.

In [2]:
# import NumPy
import numpy

Acceso a la función `norm` que calcula la norma (módulo) de un array:

In [3]:
numpy.linalg.norm

<function numpy.linalg.norm(x, ord=None, axis=None, keepdims=False)>

La función `norm` está dentro del paquete `linalg` que a su vez está dentro del paquete `numpy`

La convención para importar `NumPy` siempre es la siguiente:

In [4]:
import numpy as np

Se crea un alias del paquete `NumPy` de nombre `np`. Esta forma de organizar las funciones por medio de paquetes (espacio de nombre) ayuda a tener una legibilidad en el código y evitar ambigüedades. 

Es posible encontrar ayuda de cierto tema con la función `lookfor()`

In [5]:
np.lookfor('solve')

Search results for 'solve'
--------------------------
numpy.linalg.solve
    Solve a linear matrix equation, or system of linear scalar equations.
numpy.linalg.lstsq
    Return the least-squares solution to a linear matrix equation.
numpy.linalg.tensorsolve
    Solve the tensor equation ``a x = b`` for x.
numpy.nditer.close
    close()
numpy.linalg._umath_linalg.solve
    solve the system a x = b, on the last two dimensions, broadcast to the rest.
numpy.linalg._umath_linalg.solve1
    solve the system a x = b, for b being a vector, broadcast in the outer dimensions.
numpy.distutils.misc_util.njoin
    Join two or more pathname components +
numpy.distutils.misc_util.minrelpath
    Resolve `..` and '.' from path.
numpy.distutils.system_info.UmfpackNotFoundError
    UMFPACK sparse solver (https://www.cise.ufl.edu/research/sparse/umfpack/)
numpy.shares_memory
    Determine if two arrays share memory.
numpy.linalg.eig
    Compute the eigenvalues and right eigenvectors of a square array.
num

## Constantes y funciones matemáticas

In [6]:
np.e

2.718281828459045

In [7]:
np.pi

3.141592653589793

In [8]:
np.log(2)

0.6931471805599453

## Arrays de NumPy

Un array de `NumPy` es una colección de N elementos de la misma forma que una secuencia (lista), tienen las mismas propiedades que éstas y algunas más. Para crear un array, la forma más directa es pasar una secuencia a la función np.array().

In [9]:
np.array([1, 2, 3])

array([1, 2, 3])

Para acceder al tipo del array se utiliza el atributo `dtype`

In [10]:
np.array([1, 2, 3]).dtype

dtype('int32')

Los arrays de NumPy son homogéneos, es decir, sus elementos son del mismo tipo. Si se agregan objetos de diferente tipo a `np.array` se promueven al objeto con la mayor con mayor información. 

In [11]:
np.array([1, 2, 3.]).dtype

dtype('float64')

In [12]:
np.array([1, 2, '3'])

array(['1', '2', '3'], dtype='<U11')

`NumPy` intentará construir un array con el tipo adecuado aunque es posible forzar el tipo del array

In [13]:
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [14]:
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

Otra forma de convertir el tipo de un array es usando el método `.astype`

In [15]:
a = np.array([1., 2., 3.])
print(a.dtype)

float64


In [16]:
a.astype(int)

array([1, 2, 3])

La importancia de usar arrays de `Numpy` consiste en la eficiencia al hacer cálculos con los arrays.
* Se **vectorizan** las operaciones
* Los bucles se ejecutan en Python, las operaciones con vectores en C
* Las operaciones entre arrays de NumPy se realizan elemento a elemento

**Ejemplo:** $a_{ij} = b_{ij} + c_{ij}$

In [17]:
N,M = 100, 100
a = np.empty(10000).reshape(N, M)
b = np.random.rand(10000).reshape(N, M)
c = np.random.rand(10000).reshape(N, M)

In [18]:
%%timeit
for i in range(N):   # Se usan bucles
    for j in range (M):
        a[i,j] = b[i,j] + c[i,j]

5.69 ms ± 103 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
%%timeit
a = b + c   # Se vectoriza la operación

4.6 µs ± 154 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Indexado de arrays

El indexado consiste en seleccionar uno o más elementos de un array. Es uno de los conceptos básicos al momento de trabajar con un los array. Existen distintas técnicas de indexado que potencían los arrays.

In [20]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a[0][0]

1

In [22]:
a[0,0]

1

In [23]:
a[0:2, 0:2]

array([[1, 2],
       [4, 5]])

Los índices se indican entre corchetes justo después del array. Recordar que los índices en Python inician en 0. Si en un array de dos dimensiones se recupera el primer elemento, se obtendrá el primer renglón.

In [24]:
a[0]

array([1, 2, 3])

## Creación de arrays

Existen métodos muy variados para crear arrays:
* A partir de datos existentes: `array`, `copy`
* Unos y Ceros: `empty`, `ones`, `zeros`, `*_like`
* Rangos: `arange`, `linspace`, `logspace`, `meshgrid`
* Aleatorios: `rand`, `randn`

### Unos y Ceros

* `empty(shape)` crea un array con "basura", equivalente a  no inicializarlo, es ligeramente más rápido que `zeros()` y `ones()`
* `eye(N, N=None, k=0)` crea un array con unos en una diagonal y ceros en el resto
* `identity(n)` devuelve la matriz identidad
* Las funciones `*_like()` constituyen arrays con el mismo tamaño que otro dado

In [26]:
np.empty((3,4))

array([[4.67296746e-307, 1.69121096e-306, 1.05695083e-307,
        8.90073682e-308],
       [8.34441742e-308, 1.78022342e-306, 6.23058028e-307,
        9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
        0.00000000e+000]])

In [27]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.identity(5).astype(int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [30]:
i3 = np.identity(3)
i3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
i3.shape

(3, 3)

In [32]:
np.ones(i3.shape)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.ones_like(i3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Rangos
* `linspace(start, stop, num=10)` devuelve números equiespaciados dentro de un intervalo
* `logspace(start, stop, num=10` devuelve números equiespaciados según una escala logarítmica
* `meshgrid(x1, x2, ...)` devuelve matrices de n-coordenadas

In [34]:
np.linspace(0, 1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [35]:
np.logspace(0, 3, num=10, base=10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [36]:
x = np.linspace(0, 1, num=5)
y = np.linspace(0, 1, num=5)

xx, yy = np.meshgrid(x, y)

In [37]:
xx, yy

(array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ]]),
 array([[0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.25, 0.25, 0.25, 0.25, 0.25],
        [0.5 , 0.5 , 0.5 , 0.5 , 0.5 ],
        [0.75, 0.75, 0.75, 0.75, 0.75],
        [1.  , 1.  , 1.  , 1.  , 1.  ]]))

## Operaciones con arrays

Las **funciones universales** (`ufunc`) operan sobre arrays de NumPy elemento a elemento y siguiendo las reglas de _broadcasting_
* Funciones matemáticas: `sin`, `cos`, `sqrt`, `exp`
* Operaciones lógicas <, >, ==, ...
* Funciones lógicas: `all`, `any`, `isnan`, `allclose`

In [38]:
import numpy as np

In [39]:
a = np.arange(2 * 3)
a

array([0, 1, 2, 3, 4, 5])

In [40]:
a = a.reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])

In [ ]:
np.arange(-3, 3)

In [ ]:
np.sqrt(np.arange(-3, 3))

In [ ]:
np.arange(-3, 3).astype(complex)

In [ ]:
np.sqrt(_)

In [ ]:
a = np.arange(6)
b = np.ones(6).astype(int)
a, b

In [ ]:
# Se hace una comparación vectorizada
a < b

In [ ]:
# Verifica si hay algún valore True en el arreglo
np.any(a < b) 

In [ ]:
# Verifica si todos son verdaderos
np.all(a < b)

Los números de punto flotante no pueden ser comparados con precisión como los enteros debido a ala precisión de su representación. Para comparar arrays de floats se utiliza `isclose()` o `allclose()` especificando una tolerancia para la comparación

In [ ]:
a = np.arange(6).astype(float)
b = np.ones(6)
a, b

In [ ]:
np.isclose(a, b, rtol=1e-6)

In [ ]:
np.allclose(a,b, rtol=1e-6)

## Ejercicios

### Ejercicio 1

1. Crear un array z1 de 3x4 lleno de ceros tipo entero
2. Crear un array z2 de 3x4 lleno de ceros excepto la primera fila que serán todos unos
3. Crear un array z3 de 3x4 lleno de ceros excepto la última fila que será de rango entre 5 y 8

In [ ]:
z1 = np.zeros((3,4)).astype(int)
z1

In [ ]:
z2 = np.zeros((3, 4))
z2

In [ ]:
z2[0]

In [ ]:
z2[0 , :]

In [ ]:
z2[0, :] = np.ones(4)
z2

In [ ]:
np.ones(4)

**Nota:** Observar que puede hacerse la asignación vectorizada también. La operación siguiente se expande a la forma de la matriz.

In [ ]:
z2[1, :] = 1
z2

In [ ]:
z3 = np.zeros((3,4))
z3

In [ ]:
z3[2, :]=np.array(range(5,9))
z3

## Basics de arrays

Se pueden crear arreglos con la función `arange()`. La instancia `arange(n)` genera $n$ elementos iniciando desde $0$ hasta $n-1$. La instancia `arange(a, n)` genera $n-a$ elementos iniciando desde $a$ hasta $n-1$. La instancia `arange(a,n,s)` genera $(n-a)/s + 1$ elementos.

In [42]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(-1, 7)

array([-1,  0,  1,  2,  3,  4,  5,  6])

In [ ]:
np.arange(2, 10,2)

In [ ]:
np.arange(3, 10, 3)

## Indexado

Python crea índices de un array enumerándolos en ambos sentidos. De izquierda a derecha los índices son positivos e inician desde $0$, de derecha a izquierda los índices son negativos e inician desde $-1$.

En el sentido izquierda a derecha, para $n$ elementos en el array, los índices serán desde $0,...,n-1$.


### Ejercicio 2

In [ ]:
a = np.arange(6)
a

In [ ]:
a[1]   #Elemento con índice 1

In [ ]:
a[-1]  # El último elemento

In [ ]:
a[:]  # Recorre todos los elementos

In [ ]:
a[1:3]  # Dado a, b se especifica el intervalo [a, b)

In [ ]:
a[:]  # Recorre todos los elementos

In [ ]:
a[:2]  # Recorre del índice 0 al 1

In [ ]:
a[2:] # Recorre desde el índice 2 hasta el último  indice

In [ ]:
a[2:-1] # Recorre desde el índice 2 hasta el penúltimo índice

In [ ]:
a

In [ ]:
a[0:6:2]   # Recorre todos los índices de 2 en 2

In [ ]:
a[:6:2]   # Recorre todos los índices de 2 en 2

In [ ]:
a[::2] # Recorre todos los índices de 2 en 2

In [ ]:
a[1:6:2]  # Recorre del índice 1 al 5 de 2 en 2   

In [ ]:
a[::3] # Recorre todos los índices de 3 en 3

### Ejercicio 3


En el sentido derecha a izquierda, para $n$ elementos en el array, los índices van desde $-n,...,-1$.



In [4]:
# array con 10 elementos
# por defecto range(n) inicia desde 0 hasta n-1
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# array con n=10 elementos iniciando desde 1
# range(a,b) refiere a los enteros dentro del intervalo [a,b)
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# el primer elemento tiene índice 0
a[0]

1

In [7]:
# o bien tiene índice -10
a[-10]

1

In [8]:
# el último elemento 
a[-1]

10

In [9]:
# una rebanada (slice) del array
# array [i:j] refiere a los índices desde -10 hasta -4
a[-10:-3]

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
# los tres últimos elementos
a[-3:]

array([ 8,  9, 10])

In [ ]:
# no funciona tomar un slice hasta el índice -1
# aplica el intervalo [a,b)
a[-7:-1]

In [ ]:
# elementos con índices desde -10 hasta el -4
# tomados de 2 en 2
a[-10:-5:2]

In [ ]:
# todos los elementos
# referiremos a los elementos con índices -10 hasta -1
a[:]


In [ ]:
# equivalente al anterior
# recorre desde el primer elemento del array hasta el final
a[-10:]

In [ ]:
# desde él último elemento hasta el final
a[-1:]

In [ ]:
# recorre desde el inicio hasta el índice -4
# intervalo [-10, -3)
a[:-3]

In [ ]:
# desde el inicio hasta el primer elemento
a[:-9]

In [ ]:
# elementos con índices desde -10 hasta el -4
# tomados de 2 en 2
a[-10:-3:2]

In [ ]:
# equivalente que el anterior
a[:-3:2]

In [ ]:
# Recorre todos los elememtos tomando de 2 en 2
a[::2]

In [ ]:
# todos los elementos
# tomados de 3 en 3
a[-10::3]

In [ ]:
# equivalente al anterior
a[::3]

### Ejercicio 4

Python permite extraer elementos de un array en orden inverso (derecha a izquierda).
Para extraer elementos en sentido inverso el orden de los índices se escriben del mayor al menor.

Usando índices positivos...

In [25]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[::-1]

In [ ]:
# toma un slice desde el último hasta el 
# elemento con índice 5, intervalo [9, 4)
a[9:4:-1]

In [ ]:
# error!!
# elementos en orden inverso usando índices positivos
# se referencían en orden inverso también
a[4:9:-1]

In [ ]:
a[:4:-1]

In [ ]:
# Todos los elementos en orden inverso
a[9::-1]

In [ ]:
# elementos con índices 9 hasta 3
# tomados de 2 en 2
a[9:2:-2]

Usando índices negativos...

In [ ]:
a

In [ ]:
# Todos los elementos en sentido inverso
a[::-1]

In [ ]:
# Equivalente al anterior
a[-1::-1]

In [ ]:
a[-1:-5:-1 ]

In [ ]:
# elementos en sentido inverso de 2 en 2
a[::-2]

Combinando índices positivos y negativos

In [ ]:
a

In [ ]:
a[9:-7:-1]

In [ ]:
a[-1:3:-1]

In [ ]:
a[-1::-1]

In [ ]:
a[9::-1]

In [ ]:
a[9:-7:-2]

## Arrays bidimensionales

Un arreglo bidimensional puede entenderse como un array de arrays unidimensionales $[a_0, a_1, a_2,...,a_n]$ donde cada $a_i$ tiene $m$ elementos.

In [ ]:
a = np.arange(12).reshape(3,4)
a

In [ ]:
# array a0 elemento con índice 1
a[0,1]  # Los índices comienzan en cero

In [ ]:
# Array a0 y todos sus elementos
a[0, :]

In [ ]:
# de todos los arrays se toman los elemntos
# con índice 2.
a[:, 2]

In [ ]:
# array a0, a1
a[0 : 2 ]

In [ ]:
a

In [ ]:
# de los arrays a0, a1 se toman sus
# elementos con índice 1 
a[0 : 2 , 1]

In [ ]:
# de los arrays a0, a1 se toman
# los elementos con índices 1 y 2
a[0:2 , 1:3]

In [ ]:
a[0::]

In [ ]:
a[0::, 1]

In [ ]:
a[0::, 1:3]

In [ ]:
a[0:: , 0:: ]

In [ ]:
a = np.zeros((3, 4))
a

In [ ]:
a[0, :] = np.ones(4)   # Cambia a 1,s el primer renglón
a

In [ ]:
a[2, :] = 1   # Es equivalente a la anterior
              # La operación se expande
a

In [ ]:
a[2]   # Denota todo el renglón con índice 2

In [ ]:
a[-2]  # Denota el penúltimo renglón

In [ ]:
b = np.zeros((3, 4))

In [ ]:
b[-1] = np.arange(5, 9)
b

In [ ]:
v = np.ones(10)
v

In [ ]:
v[::2] = 2
v

In [ ]:
tablero = np.zeros((8,8))
tablero

In [ ]:
tablero[1::2, ::2] = 1
tablero

In [ ]:
tablero[::2, 1::2] = 1
tablero