In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
X = np.array([[3,7],[2,15],[10,18]])

In [3]:
X

array([[ 3,  7],
       [ 2, 15],
       [10, 18]])

In [4]:
scaler = MinMaxScaler()

In [5]:
x_normalizada = scaler.fit_transform(X)

In [6]:
print("Valores originales")
print(X)
print("Valores normalizados")
print(x_normalizada)

Valores originales
[[ 3  7]
 [ 2 15]
 [10 18]]
Valores normalizados
[[0.125      0.        ]
 [0.         0.72727273]
 [1.         1.        ]]


In [7]:
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [8]:
df = sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
label = LabelEncoder()
lb = label.fit_transform(df["sex"])
Data = df.drop("sex",axis='columns')
Data["sex"] = lb

In [10]:
Data.head()

total_bill   tip smoker  day    time  size  sex
0       16.99  1.01     No  Sun  Dinner     2    0
1       10.34  1.66     No  Sun  Dinner     3    1
2       21.01  3.50     No  Sun  Dinner     3    1
3       23.68  3.31     No  Sun  Dinner     2    1
4       24.59  3.61     No  Sun  Dinner     4    0

In [11]:
XData = Data[['total_bill','tip','sex']]

In [12]:
XData.head()

total_bill   tip  sex
0       16.99  1.01    0
1       10.34  1.66    1
2       21.01  3.50    1
3       23.68  3.31    1
4       24.59  3.61    0

In [13]:
scaler = MinMaxScaler()
XData[['total_bill']] = scaler.fit_transform(XData[['total_bill']])
XData

C:\Users\dilan\AppData\Local\Temp\ipykernel_29132\3849074665.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  XData[['total_bill']] = scaler.fit_transform(XData[['total_bill']])


total_bill   tip  sex
0      0.291579  1.01    0
1      0.152283  1.66    1
2      0.375786  3.50    1
3      0.431713  3.31    1
4      0.450775  3.61    0
..          ...   ...  ...
239    0.543779  5.92    1
240    0.505027  2.00    0
241    0.410557  2.00    1
242    0.308965  1.75    1
243    0.329074  3.00    0

[244 rows x 3 columns]

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler = StandardScaler()
ScaledData = scaler.fit_transform(XData)

In [16]:
ScaledData

array([[-3.14711305e-01, -1.43994695e+00, -1.34335316e+00],
       [-1.06323531e+00, -9.69205340e-01,  7.44405889e-01],
       [ 1.37779900e-01,  3.63355539e-01,  7.44405889e-01],
       [ 4.38315103e-01,  2.25754144e-01,  7.44405889e-01],
       [ 5.40744704e-01,  4.43019505e-01, -1.34335316e+00],
       [ 6.19536705e-01,  1.23965916e+00,  7.44405889e-01],
       [-1.23995452e+00, -7.22971264e-01,  7.44405889e-01],
       [ 7.98507107e-01,  8.81527488e-02,  7.44405889e-01],
       [-5.34203307e-01, -7.51939979e-01,  7.44405889e-01],
       [-5.63468908e-01,  1.67816714e-01,  7.44405889e-01],
       [-1.07111451e+00, -9.32994446e-01,  7.44405889e-01],
       [ 1.74175992e+00,  1.44968234e+00, -1.34335316e+00],
       [-4.91430507e-01, -1.03438495e+00,  7.44405889e-01],
       [-1.52624903e-01,  1.24660453e-03,  7.44405889e-01],
       [-5.57840908e-01,  1.57309619e-02, -1.34335316e+00],
       [ 2.01939101e-01,  6.67527044e-01,  7.44405889e-01],
       [-1.06436091e+00, -9.61963161e-01

In [17]:
ScaledData[:].std()

np.float64(1.0)